### PR TITLE
Add support for NamedRoutes

### PR DESCRIPTION
**Pull request by aveltras**
Hi,

I added support for the new NamedRoutes feature coming with Servant 0.19.

### CODE REVIEW

**Comment by marinelli** [comment]
> Hi,
> 
> I added support for the new NamedRoutes feature coming with Servant 0.19.

Interesting, I wrote the same definition :)
I think we need to fix some of the type families in the `Servant.OpenApi.Internal.TypeLevel.API` module, too.
Take a look here https://github.com/marinelli/servant-openapi3/commit/ee829b50fea0ec74e3f06dddb8ad9027c6b3bed7.
Actually, I'm not completelly sure of those definitions, I was able to verify just the `IsIn` type family. I also do not like so much all of those preprocessor's conditionals.

**Comment by aveltras** [comment]
Not sure about those type families. We use it with many endpoints on our project and the instance in that PR seems to be sufficient.

**Comment by marinelli** [comment]
> Not sure about those type families. We use it with many endpoints on our project and the instance in that PR seems to be sufficient.

If you use [`subOperations`](https://hackage.haskell.org/package/servant-openapi3-2.0.1.3/docs/src/Servant.OpenApi.Internal.html#subOperations), you'll need need it.

**Comment by marinelli** [comment]
> > Not sure about those type families. We use it with many endpoints on our project and the instance in that PR seems to be sufficient.
> 
> If you use [`subOperations`](https://hackage.haskell.org/package/servant-openapi3-2.0.1.3/docs/src/Servant.OpenApi.Internal.html#subOperations), you'll need it.

You can apply my changes here, as you wish. @maksbotan what do you think?

**Comment by maksbotan** [comment]
Merged in #24. Thanks! :)

**Pull request closed without merging**
